### ISSUE TITLE
Required functions not available/ build not possible

### ISSUE THREAD

**Issue by eeeey** [jonfink/GP#1]
Hi jonfink,

I tried to use your GP library but I couldn't manage to compile it due to the two functions "cholbacksub" and "solve_tri" which are used in the file GP.cc. These functions are not included by any header or from any external library, so it seems they are just missing.

Using Google, a search for "cholbacksub" showed exactly one hit, namely this GP.cc file, which is missing the function.

Could you take a look at this, because without those functions it is not possible to build the library and it is basically not usable, which would by a pity. I really need this library, so fixing this issue would be of great help.

Thanks,
eeeey

**Comment by locke4j** [comment]
Hi, eeeey,

I met the same problem here, have you found a solution yet?

thanks,
locke4j

**Comment by yangyangshu** [comment]
Hi  eeeey and locke4j,

 You know that, I met the same problem in the GP library. I am wondering that have you found a solution or have you known the specific purpose of the two function?

Thank you very much!

**Comment by eeeey** [comment]
Unfortunatly not, I couldn't find anything about those functions and therefore didn't use the "library" at all... Sorry, but I can't help you on this topic.

**Comment by yangyangshu** [comment]
Hi eeeey,
This library provides a C++ implementation of Gaussian process regression as described in  "Gaussian Processes for Machine Learning", so I found the book and guess the specific purpose of the two function based on page 19 in this book. I think the propose of the function cholbacksub() is to obtain the alpha, and the solve_tri() is to get the vector V. In the book, we can see the detail process to calculate the two variates. And I do some experiment, the guess may be right. If you have some interests, we can talk about it.

yang

**Comment by locke4j** [comment]
i am using libgp instead of this code，libgp works fine

发自我的 iPhone

**Comment by yangyangshu** [comment]
Dear locke4j,
Could you send me the  libgp library that you used? I just want to verify some experimental results for I have did some modification to GP master library. And it would be very kind of you if you tell me the detail about how to use the libgp library. My e-mail address is liudeyang@163.com.

Thank you very much!
Yang

**Comment by jonfink** [comment]
I just pushed an update to the library that adds support for the cholbacksub and solve_tri functions - these were part of a custom Armadillo build that I was using with some additional wrapping around LAPACK functionality. 

Note, I'm developing on OSX so right now I am directly including clapack.h from the Accelerate framework. This could be found automatically with a little CMake magic.

**Comment by jonfink** [comment]
Added find_path in CMakeLists.txt for clapack.h 

May require linking LAPACK library on linux (using Accelerate framework on testing machine right now)
